# Generated by Django 3.2.3 on 2021-06-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email Address')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('phone', models.IntegerField(unique=True, verbose_name='Phone Number')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('profile', models.TextField(blank=True, null=True, verbose_name='Profile Picture')),
                ('college', models.CharField(max_length=100, verbose_name='College Name')),
                ('roll', models.CharField(blank=True, max_length=15, null=True, verbose_name='Exam Roll Number')),
                ('otp', models.CharField(blank=True, max_length=6, null=True, verbose_name='otp')),
                ('otp_expire', models.DateTimeField(blank=True, null=True, verbose_name='OTP Expire')),
                ('verified', models.CharField(default='N', max_length=1, verbose_name='Verified')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Last Login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('feedback', models.TextField()),
            ],
        ),
    ]
